In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = np.array([60,65,70,75,80,85,90,95,100,]).reshape((-1, 1)) # temp 온도
y = np.array([50,70,100,120,150,200,250,300,350]) # sales 매출

model = LinearRegression()

model.fit(x, y)

model = LinearRegression().fit(x, y)

r_sq = model.score(x, y)

print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.9715120663650075


In [ ]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

In [5]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 25.33333333  63.16666667 101.         138.83333333 176.66666667
 214.5        252.33333333 290.16666667 328.        ]


In [32]:
temp_new = np.array([80]).reshape((-1, 1))
temp_new
model.predict(temp_new)

array([176.66666667])

In [12]:
x_new = np.arange(5).reshape((-1, 1))
x_new
y_new = model.predict(x_new)
y_new

array([-428.66666667, -421.1       , -413.53333333, -405.96666667,
       -398.4       ])

In [14]:
np.arange(5).reshape((-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
np.arange(5).reshape((1, -1)).shape

(1, 5)

In [13]:
np.arange(5)


array([0, 1, 2, 3, 4])